### ISSUE TITLE
Extension breaks all links on Youtube

### ISSUE THREAD

**Issue by ShivamSinghania** [usergit/reading-time#1]
After Youtube changed their layout, this extension breaks all links on youtube.com , clicking anything does not work while [ right-click -> Open in new Tab ] works. 

Nilo César Teixeira pointed out that the error is "Visibility monitor is not attached" in desktop_polymer.js:5346
Others have mentioned that this problem is present on Chrome on Windows, Mac and Linux.

After disabling the extension and reloading the page, Youtube works fine. No need to restart Chrome.
Please fix this bug as it may affect more than just Youtube.
BTW, who wants reading time on Youtube ? Please add functionality to block certain sites as per user's choice.

Thanks.

**Comment by usergit** [comment]
this has been fixed for youtube on the current version 1.1.1, I'll add website exclusion feature in the coming week.
